import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string, fallback?: string) => string;
}

const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home', 'nav.browse': 'Browse', 'nav.genres': 'Genres',
    'nav.community': 'Community', 'nav.my_music': 'My Music', 'nav.playlists': 'Playlists',
    'nav.history': 'History', 'nav.following': 'Following', 'nav.notifications': 'Notifications',
    'nav.profile': 'Profile', 'nav.settings': 'Settings', 'nav.get_premium': 'Get Premium',
    'nav.discover_sec': 'DISCOVER', 'nav.my_music_sec': 'MY MUSIC', 'nav.following_sec': 'FOLLOWING',
    'nav.account_sec': 'ACCOUNT', 'nav.system_sec': 'SYSTEM', 'nav.overview': 'Overview',
    'nav.users': 'Users', 'nav.songs': 'Songs', 'nav.moderation': 'Moderation',
    'nav.payments': 'Payments', 'nav.analytics': 'Analytics', 'nav.upload': 'Upload',
    'nav.dashboard': 'Dashboard', 'nav.logout': 'Logout', 'nav.favorites': 'My Music',
    'nav.subscription': 'Get Premium',
    'nav.dashboard overview': 'Dashboard Overview', 'nav.profile management': 'Profile Management',
    'nav.music uploads': 'Music Uploads', 'nav.performance & analytics': 'Performance & Analytics',
    'nav.social interaction': 'Social Interaction', 'nav.revenue & royalties': 'Revenue & Royalties',
    'nav.subscription plan': 'Subscription Plan',
    'landing.home': 'Home', 'landing.discover': 'Discover', 'landing.trending_songs': 'Trending Songs',
    'landing.artists': 'Artists', 'landing.pricing': 'Pricing', 'landing.login': 'Login',
    'landing.signup': 'Sign Up', 'landing.logout': 'Logout', 'landing.dashboard': 'Dashboard',
    'landing.hero_title': 'Discover, Stream & Promote Cameroonian Music',
    'landing.hero_desc': 'The heartbeat of Cameroonian music. Stream your favorite artists, discover new talent, and experience the cultural soundscape of 237.',
    'landing.listen_now': 'LISTEN NOW', 'landing.start_promoting': 'START PROMOTING',
    'landing.popular_tracks': 'POPULAR TRACKS', 'landing.top_artists': 'TOP ARTISTS',
    'landing.popular_genres': 'POPULAR GENRES', 'landing.subscription_plans': 'SUBSCRIPTION PLANS',
    'landing.how_it_works': 'How {name} Works',
    'landing.step1_title': '1. Artists Upload', 'landing.step1_desc': 'Register and share your tracks with the community.',
    'landing.step2_title': '2. Fans Discover', 'landing.step2_desc': 'Explore new genres and stream local favorites.',
    'landing.step3_title': '3. Grow Together', 'landing.step3_desc': 'Artists gain visibility and build their fanbase.',
    'landing.latest_releases': 'Latest Published Releases',
    'landing.latest_releases_sub': 'Freshly approved tracks from Cameroonian artists',
    'landing.view_all_songs': 'View All Songs', 'landing.why_choose_us': 'Why Choose Us',
    'landing.feat_local_title': 'Local Focus', 'landing.feat_local_desc': 'Promoting Cameroonian artists and local music culture.',
    'landing.feat_vis_title': 'Fair Visibility', 'landing.feat_vis_desc': 'Fair algorithmic visibility for emerging and established artists.',
    'landing.feat_sub_title': 'Artist Subscriptions', 'landing.feat_sub_desc': 'Revenue tools and subscription analytics for artists.',
    'landing.feat_disc_title': 'Easy Discovery', 'landing.feat_disc_desc': 'Explore genres, playlists, and curated Cameroonian music.',
    'landing.featured_artists': 'Featured Artists', 'landing.featured_artists_sub': 'Trending talent across Cameroon',
    'landing.explore_all_artists': 'Explore All Artists',
    'landing.explore_genres': 'Explore Cameroonian Genres',
    'landing.explore_genres_sub': 'Immerse yourself in authentic sonic cultures and signature styles',
    'landing.monthly_streams': 'Monthly Streams', 'landing.active_artists': 'Active Artists', 'landing.songs_uploaded': 'Songs Uploaded',
    'landing.transparent_pricing': 'Transparent Pricing', 'landing.pricing_sub': 'Choose the plan that fits your musical journey.',
    'landing.popular_badge': 'POPULAR', 'landing.get_started_free': 'Get Started Free',
    'landing.pay_momo': 'Pay via MTN MoMo', 'landing.community_says': 'What the Community Says',
    'landing.cta_heading': 'Start Promoting Your Music Today', 'landing.cta_button': 'GET STARTED',
    'landing.quick_links': 'Quick Links', 'landing.social_media': 'Social Media',
    'landing.legal_policies': 'Legal & Policies', 'landing.contact_support': 'Contact Support',
    'landing.rights_reserved': 'All rights reserved.', 'landing.coming_soon': 'Coming soon',
    'auth.welcome_back': 'Welcome Back', 'auth.login_subtitle': 'Enter your credentials to access your account',
    'auth.create_account': 'Create Account', 'auth.signup_subtitle': 'Join the Cameroonian music revolution',
    'auth.email': 'Email Address', 'auth.email_placeholder': 'Enter your email',
    'auth.password': 'Password', 'auth.password_placeholder': 'Enter your password',
    'auth.confirm_password': 'Confirm Password', 'auth.confirm_password_placeholder': 'Re-enter your password',
    'auth.full_name': 'Full Name', 'auth.artist_name': 'Artist Name',
    'auth.country': 'Country', 'auth.country_placeholder': 'Country',
    'auth.registering_as': 'I am registering as', 'auth.role_fan': 'Fan',
    'auth.role_fan_desc': 'Discover and enjoy music from Cameroonian artists',
    'auth.role_artist': 'Artist', 'auth.role_artist_desc': 'Upload and share your music with the world',
    'auth.forgot_password': 'Forgot Password?', 'auth.reset_password': 'Reset Password',
    "auth.reset_desc": "Enter your registered email address and we'll send instructions to reset your password.",
    'auth.send_reset_link': 'Send Reset Link', 'auth.login_button': 'Login to Account',
    'auth.logging_in': 'Logging in...', 'auth.signup_button': 'Create Account',
    'auth.creating_account': 'Creating account...', 'auth.have_account': 'Already have an account?',
    "auth.no_account": "Don't have an account?", 'auth.sign_up_now': 'Sign up now',
    'auth.login_link': 'Login', 'auth.back_to_home': 'Back to Home',
    'auth.or_continue_with': 'Or continue with', 'auth.or_signup_with': 'Or sign up with',
    'auth.agree_terms': 'I agree to the', 'auth.and': 'and', 'auth.password_strength': 'Password strength',
    'player.no_track': 'No track selected', 'player.select_track': 'Select a track to play', 'player.now_playing': 'Now Playing',
    'common.search_placeholder': 'Search songs, artists, playlists...', 'common.cancel': 'Cancel',
    'common.save': 'Save', 'common.delete': 'Delete', 'common.edit': 'Edit',
    'common.terms': 'Terms of Service', 'common.privacy': 'Privacy Policy', 'common.cookies': 'Cookie Policy',
    'common.language': 'Language', 'common.switch_to_fr': 'Passer au Francais', 'common.switch_to_en': 'Switch to English',
    'common.logout': 'Logout', 'common.loading': 'Loading...', 'common.saving': 'Saving...',
    'common.back_home': 'Back to Home', 'common.coming_soon_feature': 'This feature is being built. Check back soon!',
    'common.coming_soon_title': 'Coming Soon',
    'browse.nav_home': 'Home', 'browse.nav_browse': 'Browse', 'browse.nav_login': 'Login',
    'browse.hero_title': 'Discover Cameroonian Magic',
    'browse.hero_desc': 'Explore the best Makossa, Bikutsi, Afrobeat, and more.',
    'browse.search_placeholder': 'Search songs, artists, genres...', 'browse.searching': 'Searching tracks and artists...',
    'browse.discover_artists': 'Discover Artists', 'browse.discover_artists_sub': 'Browse Cameroonian music creators',
    'browse.all_music': 'Browse All Music', 'browse.tracks_available': 'tracks available',
    'browse.track_singular': 'track', 'browse.matching': 'matching',
    'browse.no_tracks_found': 'No tracks found', 'browse.no_tracks_try': 'Try a different search term or genre filter',
    'legal.back_home': 'Back to Home', 'legal.terms': 'Terms of Service', 'legal.privacy': 'Privacy Policy',
    'legal.cookies': 'Cookie Policy', 'legal.last_updated': 'Last updated: September 2026 - Effective immediately',
    'legal.rights_reserved': 'All rights reserved.',
    'legal.terms_h1': '1. Acceptance of Terms',
    'legal.terms_p1': 'Welcome to {name}. By accessing or using our website and streaming services, you agree to comply with these Terms of Service.',
    'legal.terms_h2': '2. User Accounts & Registration',
    'legal.terms_p2': 'To access certain features, you must create an account. You are responsible for maintaining the confidentiality of your login credentials.',
    'legal.terms_h3': '3. Content & Intellectual Property',
    'legal.terms_p3': 'Artists retain all intellectual property rights to the audio tracks and promotional materials they upload to {name}.',
    'legal.terms_h4': '4. Subscriptions and Payments',
    'legal.terms_p4': 'Premium subscriptions are processed securely through Mobile Money (MTN MoMo, Orange Money). All transactions are in XAF.',
    'legal.terms_h5': '5. Termination & Moderation',
    'legal.terms_p5': 'We reserve the right to suspend or terminate accounts that violate copyright laws or engage in abusive platform behavior.',
    'legal.privacy_h1': '1. Information We Collect',
    'legal.privacy_p1': 'We collect personal information you provide when registering on {name}, including your name, email, account role, and payment telephone numbers.',
    'legal.privacy_h2': '2. How We Use Your Information',
    'legal.privacy_p2': 'Your data is used to provide streaming services, maintain playlists, pay royalties, and personalize recommendations. We do not sell your data.',
    'legal.privacy_h3': '3. Data Storage & Security',
    'legal.privacy_p3': 'We use TLS/HTTPS encryption. Passwords are cryptographically hashed and never stored in plain text.',
    'legal.privacy_h4': '4. Your Rights',
    'legal.privacy_p4': 'You may request access, correction, or deletion of your account data at any time through your profile settings.',
    'legal.cookies_h1': '1. What Are Cookies',
    'legal.cookies_p1': 'Cookies are small text files placed on your device. They help ensure websites work properly and remember your playback preferences.',
    'legal.cookies_h2': '2. How We Use Cookies',
    'legal.cookies_p2': '{name} uses essential cookies to keep you logged in, remember your volume level and player queue, and protect against CSRF attacks.',
    'legal.cookies_h3': '3. Managing Cookies',
    'legal.cookies_p3': 'You can configure your browser to block cookies, though some platform features may not work correctly without them.',
    'sub.elevate': 'Elevate Your Sound Experience', 'sub.premium_plans': 'Premium Plans',
    'sub.hero_desc': 'Support Cameroonian artists directly, stream without interruptions, and listen in studio-master audio quality anywhere.',
    'sub.current_status': 'Current Status:', 'sub.secure_checkout': 'Fast & secure Mobile Money checkout (MTN MoMo & Orange Money)',
    'sub.included_features': 'Included Features:', 'sub.current_plan': 'Current Plan',
    'sub.downgrade_free': 'Downgrade to Free', 'sub.upgrade_momo': 'Upgrade with MoMo', 'sub.most_popular': 'Most Popular',
    'sub.faq_title': 'Frequently Asked Questions', 'sub.faq_q1': 'How does Mobile Money payment work?',
    'sub.faq_a1': 'Enter your MTN MoMo or Orange Money phone number. You will receive an instant USSD popup to enter your PIN and validate the transaction.',
    'sub.faq_q2': 'Can I cancel anytime?',
    "sub.faq_a2": "Yes! There are no long-term contracts. If you choose not to renew, your account switches back to the Free Fan plan.",
    'sub.faq_q3': 'How do artists earn from my subscription?',
    'sub.faq_a3': 'A major portion of every subscription fee is distributed directly to the Cameroonian artists whose songs you stream.',
    'settings.system_prefs': 'SYSTEM PREFERENCES', 'settings.account_settings': 'Account Settings',
    'settings.account_desc': 'Manage your notification alerts, visual appearance, and login security credentials',
    'settings.name': 'Name', 'settings.phone': 'Phone', 'settings.country': 'Country',
    'settings.avatar': 'Avatar', 'settings.bio': 'Bio', 'settings.save_account': 'Save Account',
    'settings.momo_title': 'MTN Mobile Money Linked Account',
    'settings.momo_desc': 'Used for 1-click subscription renewals, tipping artists, and receiving royalty payouts',
    'settings.update_momo': 'Update MoMo Number', 'settings.notif_prefs': 'Notification Preferences',
    'settings.save_prefs': 'Save Preferences', 'settings.notif_new_releases': 'New Releases',
    'settings.notif_new_releases_desc': 'Get notified when artists you follow drop new tracks',
    'settings.notif_artist_updates': 'Artist Updates', 'settings.notif_artist_updates_desc': 'Stay updated on artist news and announcements',
    'settings.notif_community': 'Community Mentions', 'settings.notif_community_desc': 'Know when someone mentions you in a discussion',
    'settings.notif_weekly': 'Weekly Digest', 'settings.notif_weekly_desc': 'A weekly summary of top tracks and activity',
    'settings.playback': 'Playback', 'settings.audio_quality': 'Audio quality',
    'settings.quality_low': 'Low', 'settings.quality_medium': 'Medium', 'settings.quality_high': 'High',
    'settings.autoplay': 'Autoplay next track', 'settings.crossfade': 'Crossfade tracks',
    'settings.privacy_security': 'Privacy & Security', 'settings.account_visibility': 'Account visibility',
    'settings.delete_account': 'Delete Account', 'settings.appearance': 'Appearance & Theme',
    'settings.dark_mode': 'CamSound Dark Mode', 'settings.dark_mode_desc': 'Signature deep green & charcoal theme',
    'settings.security_password': 'Security & Password', 'settings.current_password': 'Current Password',
    'settings.new_password': 'New Password', 'settings.confirm_new_password': 'Confirm New Password',
    'settings.current_password_placeholder': 'Your current password', 'settings.new_password_placeholder': 'Min. 8 characters',
    'settings.confirm_password_placeholder': 'Repeat your new password', 'settings.update_password': 'Update Password',
    'settings.updating': 'Updating...', 'settings.saved': 'Account settings saved.',
    'settings.save_error': 'Unable to save account settings.',
    'fan.premium_discovery': 'PREMIUM DISCOVERY', 'fan.welcome_back': 'Welcome back,',
    'fan.music_lover': 'Music Lover', 'fan.welcome_desc': 'Explore the latest sounds, artists, and trending releases in Cameroon',
    'fan.new_tracks': 'New Tracks', 'fan.total_plays': 'Total Plays',
    'fan.browse_genre': 'Browse by Genre', 'fan.browse_genre_sub': 'Filter by your favourite style',
    'fan.loading_music': 'Loading music library...', 'fan.new_releases': 'New Releases',
    'fan.new_releases_sub': 'Fresh tracks just dropped', 'fan.trending_now': 'Trending Now',
    "fan.trending_now_sub": "What's hot in Cameroon right now", 'fan.made_for_you': 'Made For You',
    'fan.made_for_you_sub': 'Handpicked playlists for your taste', 'fan.trending_artists': 'Trending Artists',
    'fan.trending_artists_sub': 'Cameroonian talents to watch', 'fan.favorite_artists': 'Favorite Artists',
    'fan.favorite_artists_sub': 'Artists in your collection',
    'notif.updates_alerts': 'UPDATES & ALERTS', 'notif.title': 'Notifications', 'notif.new_badge': 'new',
    'notif.stay_updated': 'Stay up to date with new track releases, social activity, and platform alerts',
    'notif.mark_all_read': 'Mark All Read', 'notif.marking': 'Marking...',
    'notif.loading': 'Loading notifications...',
    "notif.all_caught_up": "You're all caught up!", 'notif.no_new': 'No new notifications at the moment.',
    'genres.badge': 'EXPLORE STYLES', 'genres.title': 'Music Genres',
    'genres.subtitle': 'Explore the rich tapestry of Cameroonian musical heritage, traditional folklore and modern sub-genres',
    'genres.search_placeholder': 'Filter genres by name...',
    'genres.all_genres': 'All Genres', 'genres.songs_count': 'tracks',
    'genres.play_radio': 'Play Genre Radio', 'genres.back_to_genres': 'All Genres',
    'genres.top_tracks': 'Top Tracks in this Genre', 'genres.no_tracks': 'No songs found in this genre yet.',
    'genres.explore_more': 'Explore More Genres', 'genres.tracks_in': 'Tracks in',
    'admin.overview': 'Dashboard Overview', 'admin.moderation': 'Moderation Queue',
    'admin.reports': 'Reports', 'admin.logs': 'Admin Logs', 'admin.songs': 'Songs Management',
    'admin.artists': 'Artists Directory', 'admin.featured': 'Featured Content',
    'admin.subscriptions': 'Subscriptions', 'admin.plans': 'Subscription Plans',
    'admin.payments': 'Payments', 'admin.adRevenue': 'Ad Revenue', 'admin.withdrawals': 'Withdrawals & Payouts',
    'admin.users': 'User Directory', 'admin.settings': 'Platform Settings',
    'admin.total_users': 'Total Users', 'admin.active_artists': 'Active Artists',
    'admin.total_streams': 'Total Streams', 'admin.total_revenue': 'Platform Revenue',
    'admin.pending_moderation': 'Pending Moderation', 'admin.approve': 'Approve', 'admin.reject': 'Reject',
    'admin.export_csv': 'Export CSV', 'admin.search_placeholder': 'Search records...',
    'admin.filter_by': 'Filter by status...', 'admin.actions': 'Actions', 'admin.status': 'Status',
    'admin.name': 'Name', 'admin.email': 'Email', 'admin.role': 'Role', 'admin.created_at': 'Joined Date',
    'admin.title': 'Title', 'admin.artist': 'Artist', 'admin.genre': 'Genre', 'admin.plays': 'Plays',
    'admin.amount': 'Amount', 'admin.provider': 'Provider', 'admin.phone': 'Phone Number',
    'admin.confirm_action': 'Are you sure you want to perform this action?',
    'artist.dashboard': 'Artist Dashboard', 'artist.upload_title': 'Upload New Track',
    'artist.track_title': 'Track Title', 'artist.genre': 'Genre', 'artist.description': 'Description',
    'artist.drag_audio': 'Drag & Drop Audio File (MP3, WAV, OGG, FLAC)',
    'artist.drag_cover': 'Drag & Drop Cover Artwork (JPG, PNG, WebP)',
    'artist.upload_btn': 'Publish Track', 'artist.uploading': 'Uploading Track...',
    'artist.analytics': 'Analytics & Plays', 'artist.royalties': 'Royalties Balance',
    'artist.request_payout': 'Request MoMo Payout', 'artist.profile': 'Artist Profile',
    'artist.social_links': 'Social Media Links', 'artist.delete_confirm': 'Are you sure you want to delete this track?',
    'artist.my_uploads': 'My Uploaded Tracks', 'artist.no_uploads': 'You have not uploaded any tracks yet.',
    'artist.payout_amount': 'Payout Amount (XAF)', 'artist.payout_phone': 'MoMo Phone Number',
    'profile.followers': 'Followers', 'profile.following': 'Following', 'profile.tracks': 'Tracks',
    'profile.follow': 'Follow', 'profile.unfollow': 'Following', 'profile.tip_artist': 'Tip Artist with MoMo',
    'profile.play_all': 'Play All', 'profile.discography': 'Discography', 'profile.about': 'About',
    'profile.location': 'Location', 'profile.bio': 'Biography', 'profile.verified': 'Verified Artist',
    'profile.all_tracks': 'All Tracks', 'profile.no_tracks': 'This artist has not released any tracks yet.',
    'profile.account_suffix': 'Account',
    'momo.title': 'MTN Mobile Money', 'momo.live_simulation': '⚡ LIVE SIMULATION ENGINE',
    'momo.subscription_pkg': 'Subscription Package', 'momo.artist_cashout': 'Artist MoMo Cashout',
    'momo.gross_withdrawal': 'Gross Withdrawal:', 'momo.network_fee': 'MTN MoMo 2% Network Fee:',
    'momo.net_payout': 'Net Payout to Wallet:', 'momo.support_artist': 'Support Cameroonian Artist',
    'momo.direct_tip': 'Direct MoMo Tip for', 'momo.total_tip': 'Total Tip:',
    'momo.test_bench': 'Admin Gateway Test Bench', 'momo.health_check': 'MTN MoMo Connection Health Check',
    'momo.phone_label': 'MTN Mobile Money Phone Number', 'momo.accepted_prefixes': 'Accepted MTN prefixes: 67X, 68X, 650–654, 655–659',
    'momo.cheering_note': 'Cheering Note (Optional)', 'momo.cheer_placeholder': 'e.g. Love your song! Keep pushing!',
    'momo.security_guarantee': 'Encrypted direct integration with MTN Mobile Money Gateway',
    'momo.contacting': 'Contacting MTN MoMo...', 'momo.disburse_btn': 'Disburse {amount} FCFA via MoMo',
    'momo.pay_btn': 'Pay {amount} FCFA via MTN MoMo', 'momo.ussd_delivered': 'USSD PUSH PROMPT DELIVERED',
    'momo.auth_phone': 'Authorize on your Phone', 'momo.ussd_sent_to': 'A simulated USSD prompt was sent to',
    'momo.prompt_service': '📱 MTN MoMo Service Prompt', 'momo.confirm_cashout': 'Confirm cashout of {amount} FCFA to your MTN MoMo wallet?',
    'momo.confirm_payment': 'Authorize payment of {amount} FCFA to {platform} for {purpose}?',
    'momo.enter_pin': 'ENTER 4-DIGIT MOMO PIN:', 'momo.clear': 'Clear', 'momo.ok': 'OK ✔',
    'momo.auto_approve': 'Auto-Approve (Skip PIN)', 'momo.back': 'Back',
    'momo.validating_net': 'Validating MoMo Network...', 'momo.do_not_refresh': 'Do not refresh or close this window.',
    'momo.cashout_sent': 'MoMo Cashout Sent! 💸', 'momo.payment_confirmed': 'Payment Confirmed! 🎉',
    'momo.funds_transferred': 'Funds transferred to {phone}', 'momo.sub_active': 'Your {plan} subscription is now ACTIVE!',
    'momo.tip_transferred': 'Your tip has been transferred to {artist}!', 'momo.tx_ref': 'Transaction Ref:',
    'momo.net_operator': 'Network Operator:', 'momo.momo_cm': '🟡 MTN MoMo Cameroon',
    'momo.amount_settled': 'Amount Settled:', 'momo.sub_phone': 'Subscriber Phone:',
    'momo.date_time': 'Date & Time:', 'momo.just_now': 'Just now', 'momo.receipt_status': 'Status:',
    'momo.done_continue': 'Done & Continue', 'momo.ref_copied': 'Reference Copied to Clipboard!',
    'momo.copy_ref': 'Copy Transaction Reference',
    'momo.valid_phone_err': 'Please enter a valid 9-digit Cameroonian MTN number (starts with 6, e.g. 670 000 000)',
    'momo.min_withdrawal_err': 'Minimum withdrawal amount is 5,000 FCFA.',
    'momo.connecting_gateway': 'Connecting to MTN Cameroon MoMo Gateway...',
    'momo.authorizing_debit': 'Authorizing debit with MTN network...',
    'momo.validating_token': 'Validating secure transaction token...',
    'momo.provider_orange': 'Orange Money', 'momo.phone_number': 'MoMo Phone Number',
    'momo.phone_placeholder': '6XXXXXXXX', 'momo.amount': 'Amount to Pay', 'momo.pay_now': 'Pay with MoMo',
    'momo.ussd_prompt': 'Please check your phone for the USSD popup prompt and enter your PIN to validate.',
    'momo.processing': 'Processing mobile money payment...', 'momo.success': 'Payment Successful!',
    'momo.failed': 'Payment Failed or Cancelled', 'momo.close': 'Close',
    'comments.title': 'Community Comments', 'comments.write': 'Write a comment...',
    'comments.post': 'Post Comment', 'comments.reply': 'Reply', 'comments.delete': 'Delete',
    'comments.no_comments': 'No comments yet. Be the first to share your thoughts!',
    'fan.community': 'Community Discussions', 'fan.favorites': 'My Favorite Songs',
    'fan.following': 'Artists I Follow', 'fan.history': 'Listening History',
    'fan.playlists': 'My Playlists', 'fan.create_playlist': 'Create New Playlist',
    'fan.playlist_name': 'Playlist Name', 'fan.no_playlists': 'No playlists created yet. Create one to organize your favorite tracks!',
    'fan.no_history': 'No listening history yet. Start exploring music to build your history!',
    'fan.no_favorites': 'No favorite tracks saved yet. Click the heart icon on any song to add it here.',
    'fan.no_following': 'You are not following any artists yet. Discover trending artists and follow them!',
    'fan.profile_title': 'Fan Profile', 'fan.recent_activity': 'Recent Activity',
    'status.active': 'Active', 'status.pending': 'Pending', 'status.approved': 'Approved',
    'status.rejected': 'Rejected', 'status.verified': 'Verified', 'status.completed': 'Completed',
    'status.failed': 'Failed', 'status.blocked': 'Blocked', 'status.inactive': 'Inactive',
    'status.resolved': 'Resolved', 'status.successful': 'Successful', 'status.success': 'Success',
    'status.free': 'Free', 'status.fan': 'Fan', 'status.artist': 'Artist', 'status.admin': 'Admin',
  },
  fr: {
    'nav.home': 'Accueil', 'nav.browse': 'Explorer', 'nav.genres': 'Genres',
    'nav.community': 'Communaute', 'nav.my_music': 'Ma Musique', 'nav.playlists': 'Playlists',
    'nav.history': 'Historique', 'nav.following': 'Abonnements', 'nav.notifications': 'Notifications',
    'nav.profile': 'Profil', 'nav.settings': 'Parametres', 'nav.get_premium': 'Passer Premium',
    'nav.discover_sec': 'DECOUVRIR', 'nav.my_music_sec': 'MA MUSIQUE', 'nav.following_sec': 'ABONNEMENTS',
    'nav.account_sec': 'COMPTE', 'nav.system_sec': 'SYSTEME', 'nav.overview': "Vue d'ensemble",
    'nav.users': 'Utilisateurs', 'nav.songs': 'Morceaux', 'nav.moderation': 'Moderation',
    'nav.payments': 'Paiements', 'nav.analytics': 'Statistiques', 'nav.upload': 'Telecharger',
    'nav.dashboard': 'Tableau de bord', 'nav.logout': 'Deconnexion', 'nav.favorites': 'Ma Musique',
    'nav.subscription': 'Passer Premium',
    'nav.dashboard overview': "Vue d'ensemble", 'nav.profile management': 'Gestion du Profil',
    'nav.music uploads': 'Mes Morceaux', 'nav.performance & analytics': 'Performances & Stats',
    'nav.social interaction': 'Interactions Sociales', 'nav.revenue & royalties': 'Revenus & Royalties',
    'nav.subscription plan': "Plan d'Abonnement",
    'landing.home': 'Accueil', 'landing.discover': 'Explorer', 'landing.trending_songs': 'Morceaux Tendance',
    'landing.artists': 'Artistes', 'landing.pricing': 'Tarifs', 'landing.login': 'Connexion',
    "landing.signup": "S'inscrire", 'landing.logout': 'Deconnexion', 'landing.dashboard': 'Tableau de bord',
    'landing.hero_title': 'Decouvrez, Ecoutez et Promouvez la Musique Camerounaise',
    'landing.hero_desc': 'Le coeur battant de la musique camerounaise. Ecoutez vos artistes favoris et decouvrez de nouveaux talents.',
    'landing.listen_now': 'ECOUTER', 'landing.start_promoting': 'PROMOUVOIR',
    'landing.popular_tracks': 'TITRES POPULAIRES', 'landing.top_artists': 'MEILLEURS ARTISTES',
    'landing.popular_genres': 'GENRES POPULAIRES', "landing.subscription_plans": "OFFRES D'ABONNEMENT",
    'landing.how_it_works': 'Comment fonctionne {name}',
    'landing.step1_title': '1. Les artistes publient', 'landing.step1_desc': 'Inscrivez-vous et partagez vos titres avec la communaute.',
    'landing.step2_title': '2. Les fans decouvrent', 'landing.step2_desc': 'Explorez de nouveaux genres et ecoutez vos favoris locaux.',
    'landing.step3_title': '3. Evoluons ensemble', 'landing.step3_desc': 'Les artistes gagnent en visibilite et developpent leur public.',
    'landing.latest_releases': 'Dernieres Nouveautes',
    "landing.latest_releases_sub": "Titres fraichement approuves d'artistes camerounais",
    'landing.view_all_songs': 'Voir tous les morceaux', 'landing.why_choose_us': 'Pourquoi nous choisir',
    'landing.feat_local_title': 'Ancrage Local', 'landing.feat_local_desc': 'Promotion des artistes camerounais et de notre patrimoine musical.',
    'landing.feat_vis_title': 'Visibilite Equitable', 'landing.feat_vis_desc': 'Mise en avant equitable pour les artistes emergents et confirmes.',
    'landing.feat_sub_title': 'Abonnements Artistes', "landing.feat_sub_desc": "Outils de revenus et statistiques d'abonnements pour les artistes.",
    'landing.feat_disc_title': 'Decouverte Facile', 'landing.feat_disc_desc': 'Explorez les genres, playlists et musiques camerounaises selectionnees.',
    'landing.featured_artists': 'Artistes a la Une', 'landing.featured_artists_sub': 'Les talents qui font vibrer le Cameroun',
    'landing.explore_all_artists': 'Explorer tous les artistes',
    'landing.explore_genres': 'Explorez les Genres Camerounais',
    'landing.explore_genres_sub': 'Plongez dans des univers sonores authentiques et des styles uniques',
    'landing.monthly_streams': 'Streams Mensuels', 'landing.active_artists': 'Artistes Actifs', 'landing.songs_uploaded': 'Morceaux Telecharges',
    'landing.transparent_pricing': 'Tarifs Transparents', "landing.pricing_sub": "Choisissez l'offre adaptee a votre parcours musical.",
    'landing.popular_badge': 'POPULAIRE', 'landing.get_started_free': 'Commencer Gratuitement',
    'landing.pay_momo': 'Payer avec MTN MoMo', 'landing.community_says': 'Ce que dit la Communaute',
    'landing.cta_heading': "Commencez a Promouvoir Votre Musique Aujourd'hui",
    'landing.cta_button': 'COMMENCER', 'landing.quick_links': 'Liens Rapides',
    'landing.social_media': 'Reseaux Sociaux', 'landing.legal_policies': 'Mentions Legales',
    'landing.contact_support': 'Support Client', 'landing.rights_reserved': 'Tous droits reserves.',
    'landing.coming_soon': 'Bientot disponible',
    'auth.welcome_back': 'Bon retour', 'auth.login_subtitle': 'Entrez vos identifiants pour acceder a votre compte',
    'auth.create_account': 'Creer un Compte', 'auth.signup_subtitle': 'Rejoignez la revolution musicale camerounaise',
    'auth.email': 'Adresse E-mail', 'auth.email_placeholder': 'Entrez votre e-mail',
    'auth.password': 'Mot de passe', 'auth.password_placeholder': 'Entrez votre mot de passe',
    'auth.confirm_password': 'Confirmer le mot de passe', 'auth.confirm_password_placeholder': 'Retapez votre mot de passe',
    'auth.full_name': 'Nom complet', "auth.artist_name": "Nom d'artiste",
    'auth.country': 'Pays', 'auth.country_placeholder': 'Pays',
    "auth.registering_as": "Je m'inscris en tant que", 'auth.role_fan': 'Fan',
    'auth.role_fan_desc': 'Decouvrez et savourez la musique des artistes camerounais',
    'auth.role_artist': 'Artiste', 'auth.role_artist_desc': 'Televersez et partagez votre musique avec le monde',
    'auth.forgot_password': 'Mot de passe oublie ?', 'auth.reset_password': 'Reinitialiser le mot de passe',
    'auth.reset_desc': 'Entrez votre adresse e-mail pour recevoir les instructions de reinitialisation.',
    'auth.send_reset_link': 'Envoyer le lien', 'auth.login_button': 'Se connecter',
    'auth.logging_in': 'Connexion en cours...', 'auth.signup_button': 'Creer mon compte',
    'auth.creating_account': 'Creation du compte...', 'auth.have_account': 'Vous avez deja un compte ?',
    "auth.no_account": "Vous n'avez pas de compte ?", "auth.sign_up_now": "S'inscrire maintenant",
    'auth.login_link': 'Connexion', "auth.back_to_home": "Retour a l'accueil",
    'auth.or_continue_with': 'Ou continuer avec', 'auth.or_signup_with': 'Ou vous inscrire avec',
    "auth.agree_terms": "J'accepte les", 'auth.and': 'et la', 'auth.password_strength': 'Niveau de securite',
    'player.no_track': 'Aucun morceau selectionne', 'player.select_track': 'Selectionnez un titre pour ecouter', 'player.now_playing': 'Lecture en cours',
    'common.search_placeholder': 'Rechercher morceaux, artistes, playlists...', 'common.cancel': 'Annuler',
    'common.save': 'Enregistrer', 'common.delete': 'Supprimer', 'common.edit': 'Modifier',
    "common.terms": "Conditions d'utilisation", 'common.privacy': 'Politique de confidentialite',
    'common.cookies': 'Politique des cookies', 'common.language': 'Langue',
    'common.switch_to_fr': 'Passer au Francais', 'common.switch_to_en': 'Switch to English',
    'common.logout': 'Deconnexion', 'common.loading': 'Chargement...', 'common.saving': 'Enregistrement...',
    "common.back_home": "Retour a l'accueil",
    'common.coming_soon_feature': 'Cette fonctionnalite est en cours de developpement. Revenez bientot !',
    'common.coming_soon_title': 'Bientot disponible',
    'browse.nav_home': 'Accueil', 'browse.nav_browse': 'Explorer', 'browse.nav_login': 'Connexion',
    'browse.hero_title': 'Decouvrez la Magie Camerounaise',
    'browse.hero_desc': 'Explorez le meilleur du Makossa, Bikutsi, Afrobeat, et bien plus.',
    'browse.search_placeholder': 'Rechercher morceaux, artistes, genres...', 'browse.searching': 'Recherche de morceaux et artistes...',
    'browse.discover_artists': 'Decouvrir des Artistes', 'browse.discover_artists_sub': 'Parcourez les createurs de musique camerounaise',
    'browse.all_music': 'Toute la Musique', 'browse.tracks_available': 'morceaux disponibles',
    'browse.track_singular': 'morceau', 'browse.matching': 'correspondant a',
    'browse.no_tracks_found': 'Aucun morceau trouve', 'browse.no_tracks_try': 'Essayez un autre terme ou filtre de genre',
    "legal.back_home": "Retour a l'accueil", "legal.terms": "Conditions d'utilisation",
    'legal.privacy': 'Politique de confidentialite', 'legal.cookies': 'Politique des cookies',
    'legal.last_updated': 'Mis a jour : septembre 2026 - Applicable immediatement', 'legal.rights_reserved': 'Tous droits reserves.',
    'legal.terms_h1': '1. Acceptation des Conditions',
    "legal.terms_p1": "Bienvenue sur {name}. En accedant a notre site web et services de streaming, vous acceptez les presentes Conditions d'utilisation.",
    'legal.terms_h2': '2. Comptes Utilisateurs & Inscription',
    "legal.terms_p2": "Pour acceder a certaines fonctionnalites, vous devez creer un compte. Vous etes responsable de la confidentialite de vos identifiants.",
    'legal.terms_h3': '3. Contenu & Propriete Intellectuelle',
    'legal.terms_p3': 'Les artistes conservent tous les droits de propriete intellectuelle sur les pistes audio televersees sur {name}.',
    'legal.terms_h4': '4. Abonnements et Paiements',
    'legal.terms_p4': 'Les abonnements sont traites via Mobile Money (MTN MoMo, Orange Money). Toutes les transactions sont en XAF.',
    'legal.terms_h5': '5. Resiliation & Moderation',
    "legal.terms_p5": "Nous nous reservons le droit de suspendre les comptes qui violent les lois sur le droit d'auteur.",
    'legal.privacy_h1': '1. Informations Collectees',
    'legal.privacy_p1': 'Nous collectons les informations fournies lors de votre inscription sur {name}, notamment votre nom, e-mail et numeros de telephone.',
    'legal.privacy_h2': '2. Utilisation de Vos Donnees',
    'legal.privacy_p2': 'Vos donnees sont utilisees pour fournir les services de streaming et personnaliser les recommandations. Nous ne vendons pas vos donnees.',
    'legal.privacy_h3': '3. Stockage & Securite des Donnees',
    'legal.privacy_p3': 'Nous utilisons TLS/HTTPS. Les mots de passe sont hasches et jamais stockes en clair.',
    'legal.privacy_h4': '4. Vos Droits',
    "legal.privacy_p4": "Vous pouvez demander l'acces, la correction ou la suppression de vos donnees via les parametres de votre profil.",
    'legal.cookies_h1': '1. Que Sont les Cookies ?',
    'legal.cookies_p1': 'Les cookies sont de petits fichiers texte places sur votre appareil pour assurer le bon fonctionnement des sites.',
    'legal.cookies_h2': '2. Utilisation des Cookies',
    'legal.cookies_p2': '{name} utilise des cookies pour vous maintenir connecte, memoriser votre volume et vous proteger contre les attaques CSRF.',
    'legal.cookies_h3': '3. Gestion des Cookies',
    'legal.cookies_p3': 'Vous pouvez configurer votre navigateur pour bloquer les cookies, mais certaines fonctionnalites pourraient ne pas fonctionner.',
    'sub.elevate': 'Elevez Votre Experience Sonore', 'sub.premium_plans': 'Plans Premium',
    "sub.hero_desc": "Soutenez directement les artistes camerounais, ecoutez sans interruptions et profitez d'une qualite audio studio.",
    'sub.current_status': 'Statut actuel :', 'sub.secure_checkout': 'Paiement rapide et securise via Mobile Money (MTN MoMo & Orange Money)',
    'sub.included_features': 'Fonctionnalites incluses :', 'sub.current_plan': 'Plan Actuel',
    'sub.downgrade_free': 'Passer au plan Gratuit', 'sub.upgrade_momo': 'Passer Premium avec MoMo', 'sub.most_popular': 'Le Plus Populaire',
    'sub.faq_title': 'Questions Frequentes', 'sub.faq_q1': 'Comment fonctionne le paiement Mobile Money ?',
    'sub.faq_a1': 'Entrez votre numero MTN MoMo ou Orange Money. Vous recevrez une demande USSD sur votre telephone pour valider la transaction.',
    'sub.faq_q2': 'Puis-je annuler a tout moment ?',
    "sub.faq_a2": "Oui ! Il n'y a pas d'engagement. Si vous ne renouvelez pas, votre compte repasse au plan Fan Gratuit a la fin de la periode.",
    'sub.faq_q3': 'Comment les artistes gagnent-ils grace a mon abonnement ?',
    'sub.faq_a3': 'Une grande partie de chaque abonnement est distribuee directement aux artistes camerounais dont vous ecoutez les morceaux.',
    'settings.system_prefs': 'PREFERENCES SYSTEME', 'settings.account_settings': 'Parametres du Compte',
    "settings.account_desc": "Gerez vos alertes de notifications, l'apparence visuelle et vos identifiants de connexion",
    'settings.name': 'Nom', 'settings.phone': 'Telephone', 'settings.country': 'Pays',
    'settings.avatar': 'Avatar', 'settings.bio': 'Biographie', 'settings.save_account': 'Enregistrer le Compte',
    'settings.momo_title': 'Compte MTN Mobile Money Lie',
    "settings.momo_desc": "Utilise pour les renouvellements d'abonnement en 1 clic et la reception des royalties",
    'settings.update_momo': 'Mettre a jour le numero MoMo', 'settings.notif_prefs': 'Preferences de Notifications',
    'settings.save_prefs': 'Enregistrer les preferences', 'settings.notif_new_releases': 'Nouvelles Sorties',
    'settings.notif_new_releases_desc': 'Soyez notifie quand les artistes que vous suivez sortent de nouveaux morceaux',
    'settings.notif_artist_updates': 'Actualites des Artistes', 'settings.notif_artist_updates_desc': 'Restez informe des nouvelles et annonces des artistes',
    'settings.notif_community': 'Mentions Communautaires', 'settings.notif_community_desc': 'Sachez quand quelqu un vous mentionne dans une discussion',
    'settings.notif_weekly': 'Digest Hebdomadaire', 'settings.notif_weekly_desc': 'Un resume hebdomadaire des meilleurs morceaux et de l activite',
    'settings.playback': 'Lecture', 'settings.audio_quality': 'Qualite audio',
    'settings.quality_low': 'Faible', 'settings.quality_medium': 'Moyenne', 'settings.quality_high': 'Elevee',
    'settings.autoplay': 'Lecture automatique du morceau suivant', 'settings.crossfade': 'Fondu enchaine entre morceaux',
    'settings.privacy_security': 'Confidentialite & Securite', 'settings.account_visibility': 'Visibilite du compte',
    'settings.delete_account': 'Supprimer le compte', 'settings.appearance': 'Apparence & Theme',
    'settings.dark_mode': 'Mode Sombre CamSound', 'settings.dark_mode_desc': 'Theme vert profond et anthracite signature',
    'settings.security_password': 'Securite & Mot de passe', 'settings.current_password': 'Mot de passe actuel',
    'settings.new_password': 'Nouveau mot de passe', 'settings.confirm_new_password': 'Confirmer le nouveau mot de passe',
    'settings.current_password_placeholder': 'Votre mot de passe actuel', 'settings.new_password_placeholder': 'Min. 8 caracteres',
    'settings.confirm_password_placeholder': 'Repetez votre nouveau mot de passe', 'settings.update_password': 'Mettre a jour le mot de passe',
    'settings.updating': 'Mise a jour...', 'settings.saved': 'Parametres du compte enregistres.',
    "settings.save_error": "Impossible d'enregistrer les parametres du compte.",
    'fan.premium_discovery': 'DECOUVERTE PREMIUM', 'fan.welcome_back': 'Bon retour,',
    'fan.music_lover': 'Melomane', 'fan.welcome_desc': 'Explorez les derniers sons, artistes et sorties tendance au Cameroun',
    'fan.new_tracks': 'Nouveaux Morceaux', 'fan.total_plays': 'Ecoutes Totales',
    'fan.browse_genre': 'Explorer par Genre', 'fan.browse_genre_sub': 'Filtrez par votre style prefere',
    'fan.loading_music': 'Chargement de la bibliotheque musicale...', 'fan.new_releases': 'Nouvelles Sorties',
    'fan.new_releases_sub': 'Des morceaux fraichement publies', 'fan.trending_now': 'Tendances du Moment',
    'fan.trending_now_sub': 'Ce qui est populaire au Cameroun en ce moment', 'fan.made_for_you': 'Fait Pour Vous',
    'fan.made_for_you_sub': 'Des playlists selectionnees selon vos gouts', 'fan.trending_artists': 'Artistes Tendance',
    'fan.trending_artists_sub': 'Les talents camerounais a suivre', 'fan.favorite_artists': 'Artistes Favoris',
    'fan.favorite_artists_sub': 'Les artistes de votre collection',
    'notif.updates_alerts': 'MISES A JOUR & ALERTES', 'notif.title': 'Notifications', 'notif.new_badge': 'nouvelles',
    "notif.stay_updated": "Restez informe des nouvelles sorties, de l'activite sociale et des alertes de la plateforme",
    'notif.mark_all_read': 'Tout marquer comme lu', 'notif.marking': 'Marquage...',
    'notif.loading': 'Chargement des notifications...',
    'notif.all_caught_up': 'Vous etes a jour !', 'notif.no_new': 'Aucune nouvelle notification pour le moment.',
    'genres.badge': 'EXPLORER LES STYLES', 'genres.title': 'Genres Musicaux',
    'genres.subtitle': 'Decouvrez la richesse du patrimoine musical camerounais, du folklore traditionnel aux sous-genres modernes',
    'genres.search_placeholder': 'Filtrer les genres par nom...',
    'genres.all_genres': 'Tous les genres', 'genres.songs_count': 'morceaux',
    'genres.play_radio': 'Lancer la Radio du Genre', 'genres.back_to_genres': 'Tous les Genres',
    'genres.top_tracks': 'Meilleurs Titres de ce Genre', 'genres.no_tracks': 'Aucun morceau trouve dans ce genre pour le moment.',
    'genres.explore_more': 'Explorer d autres genres', 'genres.tracks_in': 'Morceaux en',
    'admin.overview': "Vue d'ensemble", 'admin.moderation': 'File de Moderation',
    'admin.reports': 'Rapports & Signalements', 'admin.logs': "Journaux d'Administration",
    'admin.songs': 'Gestion des Morceaux', 'admin.artists': 'Repertoire des Artistes',
    'admin.featured': 'Contenu a la Une', 'admin.subscriptions': 'Abonnements',
    'admin.plans': "Offres d'Abonnement", 'admin.payments': 'Paiements',
    'admin.adRevenue': 'Revenus Publicitaires', 'admin.withdrawals': 'Retraits & Versements',
    'admin.users': 'Repertoire Utilisateurs', 'admin.settings': 'Parametres de la Plateforme',
    'admin.total_users': 'Utilisateurs Totaux', 'admin.active_artists': 'Artistes Actifs',
    'admin.total_streams': 'Ecoutes Totales', 'admin.total_revenue': 'Revenus Plateforme',
    'admin.pending_moderation': 'En Attente de Moderation', 'admin.approve': 'Approuver',
    'admin.reject': 'Rejeter', 'admin.export_csv': 'Exporter CSV',
    'admin.search_placeholder': 'Rechercher des enregistrements...',
    'admin.filter_by': 'Filtrer par statut...', 'admin.actions': 'Actions', 'admin.status': 'Statut',
    'admin.name': 'Nom', 'admin.email': 'E-mail', 'admin.role': 'Role', 'admin.created_at': "Date d'Inscription",
    'admin.title': 'Titre', 'admin.artist': 'Artiste', 'admin.genre': 'Genre', 'admin.plays': 'Ecoutes',
    'admin.amount': 'Montant', 'admin.provider': 'Operateur', 'admin.phone': 'Telephone',
    'admin.confirm_action': 'Etes-vous sur de vouloir effectuer cette action ?',
    'artist.dashboard': 'Tableau de Bord Artiste', 'artist.upload_title': 'Publier un Nouveau Morceau',
    'artist.track_title': 'Titre du Morceau', 'artist.genre': 'Genre', 'artist.description': 'Description',
    'artist.drag_audio': 'Glissez-deposez votre fichier audio (MP3, WAV, OGG, FLAC)',
    'artist.drag_cover': 'Glissez-deposez votre pochette (JPG, PNG, WebP)',
    'artist.upload_btn': 'Publier le Morceau', 'artist.uploading': 'Publication du morceau...',
    'artist.analytics': 'Performances & Ecoutes', 'artist.royalties': 'Solde des Royalties',
    'artist.request_payout': 'Demander un Retrait MoMo', 'artist.profile': 'Profil Artiste',
    'artist.social_links': 'Liens Reseaux Sociaux', 'artist.delete_confirm': 'Etes-vous sur de vouloir supprimer ce morceau ?',
    'artist.my_uploads': 'Mes Morceaux Publies', 'artist.no_uploads': "Vous n'avez pas encore publie de morceaux.",
    'artist.payout_amount': 'Montant du Retrait (XAF)', 'artist.payout_phone': 'Numero Mobile Money',
    'profile.followers': 'Abonnes', 'profile.following': 'Abonnements', 'profile.tracks': 'Morceaux',
    'profile.follow': 'Suivre', 'profile.unfollow': 'Abonne(e)', 'profile.tip_artist': 'Envoyer un Pourboire MoMo',
    'profile.play_all': 'Tout Ecouter', 'profile.discography': 'Discographie', 'profile.about': 'A Propos',
    'profile.location': 'Localisation', 'profile.bio': 'Biographie', 'profile.verified': 'Artiste Verifie',
    'profile.all_tracks': 'Tous les Morceaux', 'profile.no_tracks': "Cet artiste n'a pas encore publie de morceau.",
    'profile.account_suffix': 'Compte',
    'momo.title': 'MTN Mobile Money', 'momo.live_simulation': '⚡ MOTEUR DE SIMULATION EN DIRECT',
    'momo.subscription_pkg': "Formule d'Abonnement", 'momo.artist_cashout': 'Retrait MoMo Artiste',
    'momo.gross_withdrawal': 'Retrait Brut :', 'momo.network_fee': 'Frais reseau MTN MoMo 2% :',
    'momo.net_payout': 'Montant Net au Portefeuille :', 'momo.support_artist': 'Soutenir un Artiste Camerounais',
    'momo.direct_tip': 'Pourboire MoMo direct pour', 'momo.total_tip': 'Pourboire Total :',
    'momo.test_bench': 'Banc de Test Passerelle Admin', 'momo.health_check': 'Verification de Connexion MTN MoMo',
    'momo.phone_label': 'Numero de Telephone MTN Mobile Money', 'momo.accepted_prefixes': 'Prefixes MTN acceptes : 67X, 68X, 650–654, 655–659',
    'momo.cheering_note': "Message d'Encouragement (Facultatif)", 'momo.cheer_placeholder': 'ex. J adore ta chanson ! Continue comme ca !',
    'momo.security_guarantee': 'Integration directe chiffree avec la passerelle MTN Mobile Money',
    'momo.contacting': 'Connexion a MTN MoMo...', 'momo.disburse_btn': 'Verser {amount} FCFA via MoMo',
    'momo.pay_btn': 'Payer {amount} FCFA via MTN MoMo', 'momo.ussd_delivered': 'NOTIFICATION USSD ENVOYEE',
    'momo.auth_phone': 'Autorisez sur votre Telephone', 'momo.ussd_sent_to': 'Une notification USSD simulee a ete envoyee au',
    'momo.prompt_service': '📱 Invite de Service MTN MoMo', 'momo.confirm_cashout': 'Confirmer le retrait de {amount} FCFA vers votre portefeuille MTN MoMo ?',
    'momo.confirm_payment': 'Autoriser le paiement de {amount} FCFA a {platform} pour {purpose} ?',
    'momo.enter_pin': 'ENTREZ VOTRE CODE PIN MOMO A 4 CHIFFRES :', 'momo.clear': 'Effacer', 'momo.ok': 'OK ✔',
    'momo.auto_approve': 'Approuver Auto (Ignorer le PIN)', 'momo.back': 'Retour',
    'momo.validating_net': 'Validation du Reseau MoMo...', 'momo.do_not_refresh': 'Ne fermez pas et ne rafraichissez pas cette fenetre.',
    'momo.cashout_sent': 'Retrait MoMo Envoye ! 💸', 'momo.payment_confirmed': 'Paiement Confirme ! 🎉',
    'momo.funds_transferred': 'Fonds transferes au {phone}', 'momo.sub_active': 'Votre abonnement {plan} est maintenant ACTIF !',
    'momo.tip_transferred': 'Votre pourboire a ete envoye a {artist} !', 'momo.tx_ref': 'Ref. Transaction :',
    'momo.net_operator': 'Operateur Reseau :', 'momo.momo_cm': '🟡 MTN MoMo Cameroun',
    'momo.amount_settled': 'Montant Regle :', 'momo.sub_phone': 'Telephone Abonne :',
    'momo.date_time': 'Date et Heure :', 'momo.just_now': 'A l instant', 'momo.receipt_status': 'Statut :',
    'momo.done_continue': 'Terminer et Continuer', 'momo.ref_copied': 'Reference copiee dans le presse-papier !',
    'momo.copy_ref': 'Copier la Reference de Transaction',
    'momo.valid_phone_err': 'Veuillez entrer un numero MTN camerounais valide a 9 chiffres (commence par 6, ex. 670 000 000)',
    'momo.min_withdrawal_err': 'Le montant minimum de retrait est de 5 000 FCFA.',
    'momo.connecting_gateway': 'Connexion a la passerelle MTN MoMo Cameroun...',
    'momo.authorizing_debit': 'Autorisation du debit aupres du reseau MTN...',
    'momo.validating_token': 'Validation du jeton de transaction securise...',
    'momo.provider_orange': 'Orange Money', 'momo.phone_number': 'Numero Mobile Money',
    'momo.phone_placeholder': '6XXXXXXXX', 'momo.amount': 'Montant a Payer', 'momo.pay_now': 'Payer avec MoMo',
    'momo.ussd_prompt': 'Veuillez verifier votre telephone pour valider la demande USSD avec votre code secret PIN.',
    'momo.processing': 'Traitement du paiement en cours...', 'momo.success': 'Paiement Reussi !',
    'momo.failed': 'Echec ou Annulation du Paiement', 'momo.close': 'Fermer',
    'comments.title': 'Commentaires de la Communaute', 'comments.write': 'Ecrire un commentaire...',
    'comments.post': 'Publier le Commentaire', 'comments.reply': 'Repondre', 'comments.delete': 'Supprimer',
    'comments.no_comments': 'Aucun commentaire pour le moment. Soyez le premier a donner votre avis !',
    'fan.community': 'Echanges Communautaires', 'fan.favorites': 'Mes Morceaux Favoris',
    'fan.following': 'Artistes Suivis', 'fan.history': "Historique d'Ecoute",
    'fan.playlists': 'Mes Playlists', 'fan.create_playlist': 'Creer une Playlist',
    'fan.playlist_name': 'Nom de la Playlist', 'fan.no_playlists': 'Aucune playlist creee pour le moment. Creez-en une pour organiser vos morceaux favoris !',
    'fan.no_history': "Aucun historique d'ecoute pour le moment. Explorez la musique pour enrichir votre historique !",
    'fan.no_favorites': 'Aucun morceau favori pour le moment. Cliquez sur le coeur pour ajouter des titres ici.',
    'fan.no_following': "Vous ne suivez aucun artiste pour le moment. Decouvrez les artistes du moment et abonnez-vous !",
    'fan.profile_title': 'Profil Fan', 'fan.recent_activity': 'Activite Recente',
    'status.active': 'Actif', 'status.pending': 'En Attente', 'status.approved': 'Approuve',
    'status.rejected': 'Rejete', 'status.verified': 'Verifie', 'status.completed': 'Termine',
    'status.failed': 'Echoue', 'status.blocked': 'Bloque', 'status.inactive': 'Inactif',
    'status.resolved': 'Resolu', 'status.successful': 'Reussi', 'status.success': 'Succes',
    'status.free': 'Gratuit', 'status.fan': 'Fan', 'status.artist': 'Artiste', 'status.admin': 'Administrateur',
  },
};

const LANG_STORAGE_KEY = 'camsound_lang';

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  toggleLanguage: () => {},
  t: (key: string, fallback?: string) => fallback || key,
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem(LANG_STORAGE_KEY);
    if (saved === 'fr' || saved === 'en') return saved;
    const browserLang = navigator.language?.toLowerCase() || '';
    if (browserLang.startsWith('fr')) return 'fr';
    return 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    try {
      localStorage.setItem(LANG_STORAGE_KEY, lang);
      document.documentElement.lang = lang;
    } catch {}
  };

  const toggleLanguage = () => {
    setLanguage(language === 'en' ? 'fr' : 'en');
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string, fallback?: string): string => {
    const translation = TRANSLATIONS[language]?.[key];
    if (translation !== undefined) return translation;
    const enFallback = TRANSLATIONS['en']?.[key];
    if (enFallback !== undefined) return enFallback;
    return fallback || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
